### ISSUE TITLE
How to mock the context

### ISSUE THREAD

**Issue by gandarain** [ReactNativeSchool/getting-started-react-navigation-v5#3]
Hai, thanks for your great video.
I have some issue here with jest and context. Jest cant read my context and always return like this. Can you help me?
![Screen Shot 2020-09-29 at 15 15 57](https://user-images.githubusercontent.com/27923352/94531372-af8b6500-0266-11eb-9b39-b1a916edc844.png)

I will send the code if u need.
Thanks.

**Comment by spencercarli** [comment]
Make sure to render your WelcomeContext.Provider in your tests.

**Comment by gandarain** [comment]
Thanks for your solution bro, finally I can pass this error.
I just put {} in my context.js, like this

````
import React, {useContext} from 'react'

export const AuthContext = React.createContext({})
export const WelcomeContext = React.createContext({})
export const GuestContext = React.createContext({})

// export default WelcomeContext
export const useAuthContext = () => useContext(AuthContext)
export const useWelcomeContext = () => useContext(WelcomeContext)
export const useGuestContext = () => useContext(GuestContext)
````

Thanks for your great video.
